### ISSUE TITLE
How do you keep running the script in the background?

### ISSUE THREAD

**Issue by mukundzare** [javahippie/slack-the-music#1]
As far as I can see, the only entrypoint is directly calling the script from shell with a `token` as a parameter. Once called, it will execute the task and exit. How do you then keep calling the script for the entirety of your music listening? Does the script run as a service or cronjob or...etc?

**Comment by javahippie** [comment]
Hi @mukundzare, sorry for the late answer!

I thought about adding a loop-mechanism to the script, but in the end these types of scripts are often managed by the operating system, e.g. with systemd. On my Mac I use the tool `watch` to call the script in intervals:

```
watch -n 29 ./stm.clj -t <THE_TOKEN>
```

**Comment by mukundzare** [comment]
That sounds nice and easy. An even better and a quick one-time solution might be a crontab to fully automate it, right?

**Comment by javahippie** [comment]
Yes, that would be an even more robust solution!
