### ISSUE TITLE
How to select status emojis?

### ISSUE THREAD

**Issue by difigue** [javahippie/slack-the-music#3]
Hey! Great job with the script, it works really good. I'd like to know how to change the pool of emojis the script is choosing from to post as status. Is it possible to assign workspace exclusive's emojis too? Thanks!!

**Comment by javahippie** [comment]
Hi, thank you very much for your comment!

You can add all the emoji with the `:emoji-name:` syntax you can use in Slack. They are located in this function, and workspace-emoji do work:

```clojure
(defn get-emoji [genre]
  (case genre
    "Metal" ":the_horns:"
    "Jazz" ":trumpet:"
    "Alternative" ":broccoli:"
    "Rock" ":guitar:"
    ":headphones:"))
```
